# config/packages/doctrine.yaml

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7' # Remplacez par votre version MySQL, par ex. '8.0' si vous utilisez MySQL 8
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

