# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ["*"]
        allow_credentials: true
        allow_methods: ["GET", "OPTIONS", "POST", "PATCH", "PUT", "DELETE"]
        allow_headers: ["Content-Type", "Authorization"]
        expose_headers: ["Link"]
        max_age: 3600
    paths:
        "^/":
            allow_origin: ["*"]
            allow_credentials: true
            allow_methods: ["GET", "OPTIONS", "POST", "PATCH", "PUT", "DELETE"]
            allow_headers: ["Content-Type", "Authorization"]
            expose_headers: ["Link"]
            max_age: 3600
