security:
    enable_authenticator_manager: true

    # Configuration des règles de hachage de mot de passe pour User
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Fournisseurs utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: test

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Firewall API ouvert sans sécurité
        api:
            pattern: ^/api
            stateless: true
            security: false # Option pour désactiver la sécurité

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }