# Routes pour la gestion des inscriptions
registration:
    path: /api/register
    controller: App\Controller\RegistrationController::register

login:
    path: /api/login
    controller: App\Controller\SecurityController::login

profile:
    path: /api/user-info/{id}
    controller: App\Controller\SecurityController::getUserInfo
    methods: [GET]
profileUpdate:
    path: /api/update-user/{id}
    controller: App\Controller\SecurityController::updateUserInfo
    methods: ["PATCH"]
# Routes pour la gestion des messages


api_message_list:
    path: /api/messages
    controller: App\Controller\MessageController::list
    methods: [GET]

# Routes pour la gestion des conversations
create_conversation:
    path: /api/conversation
    controller: App\Controller\ConversationController::createConversation
    methods: [POST]

list_conversations:
    path: /api/conversations/{id}
    controller: App\Controller\ConversationController::listConversations
    methods: [GET]

# Routes pour la gestion des conversations de groupe
create_group_conversation:
    path: /api/group-conversation
    controller: App\Controller\ConversationController::createGroupConversation
    methods: [POST]

list_users:
    path: /api/users
    controller: App\Controller\UserController::listUsers
    methods: [GET]

list_commissions:
    path: /api/commissions
    controller: App\Controller\CommissionController::listCommissions
    methods: [GET]

create_commission:
    path: /api/commissions
    controller: App\Controller\CommissionController::createCommission
    methods: [POST]

send_message:
    path: /api/message
    controller: App\Controller\MessageController::sendMessage
    methods: [POST]

get_global_messages:
    path: /api/messages/global
    controller: App\Controller\MessageController::getGlobalMessages
    methods: [GET]

get_commission_messages:
    path: /api/messages/commission/{id}
    controller: App\Controller\MessageController::getCommissionMessages
    methods: [GET]

get_notifications:
    path: /api/notifications
    controller: App\Controller\NotificationController::getNotifications
    methods: [GET]

update_notifications:
    path: /api/notifications
    controller: App\Controller\NotificationController::updateNotifications
    methods: [POST]